(function(g){var window=this;var HZ=function(a){a.g||(a.g=new g.So,g.I(a,a.g));return a.g},IZ=function(a){a.N("cardstatechange",a.rd()&&a.xe()?1:0)},JZ=function(a){var b=g.Oh(a);
a=g.Wh(a);return new g.qh(b.x,b.y,a.width,a.height)},KZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},LZ=function(a){return"none"!=a.style.display},MZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Dna=function(a){var b=g.Ih(a,"fontSize");
var c=(c=b.match(Ana))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Pd){if(String(c)in Bna)return MZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Cna)return a=a.parentNode,c=g.Ih(a,"fontSize"),MZ(a,b==c?"1em":b)}c=g.Ud("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.$d(c);return b},Ena=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Mk&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.jd("pollChoiceIndex"))},PZ=function(a){a=g.Qa(a);
delete NZ[a];g.Yb(NZ)&&OZ&&OZ.stop()},QZ=function(){OZ||(OZ=new g.N(function(){Fna()},20));
var a=OZ;a.isActive()||a.start()},Fna=function(){var a=(0,g.D)();
g.Kb(NZ,function(b){RZ(b,a)});
g.Yb(NZ)||QZ()},SZ=function(a,b){g.tf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},TZ=function(a,b,c,d){g.no.call(this);
if(!g.La(a)||!g.La(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.B=d;this.coords=[];this.progress=this.D=0;this.A=null},RZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;UZ(a,a.progress);1==a.progress?(a.g=0,PZ(a),a.Wc(),a.l()):1==a.g&&a.Ar()},UZ=function(a,b){g.Na(a.B)&&(b=a.B(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},VZ=function(a,b,c,d,e){TZ.call(this,b,c,d,e);
this.element=a},WZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
VZ.call(this,a,b,c,d,e)},Gna=function(a){return Math.pow(a,3)},Hna=function(a){return 3*a*a-2*a*a*a},XZ=function(a){g.H.call(this);
this.i=a||window;this.g=[]},Ina=function(a,b,c,d){c=(0,g.y)(c,d||a.i);
b=g.ds(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},YZ=function(a,b){(0,g.B)(b,function(c){g.Rs("visualElementShown",{csn:a,
ve:g.$s(c),eventType:4},g.Ws,void 0,void 0)})},ZZ=function(a,b){(0,g.B)(b,function(c){g.Rs("visualElementHidden",{csn:a,
ve:g.$s(c),eventType:8},g.Ws,void 0,void 0)})},$Z=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Xc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={BD:a.impression,click:a.click,close:a.close,XL:a.teaser_impression,Cs:a.teaser_click};b=b.tracking_params||{};this.A=g.Zs(b.card);this.D=g.Zs(b.teaser);this.u=g.Zs(b.icon)},a_=function(a,b){g.Uf.call(this);
this.Cj=a;this.Kp=b;this[g.vf]=!1},f_=function(a,b,c,d){a_.call(this,a,b);
a=this.Kp;b=this.ha();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.v(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Jna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Kp;a=this.ha();if(d instanceof b_)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof c_){b="lg-"+d.u+"-"+d.B+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=d_(c,"linearGradient",{x1:d.u,y1:d.B,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ga(d.l)&&(f+=";stop-opacity:"+d.l);f=d_(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ga(d.o)&&(f+=";stop-opacity:"+d.o);d=d_(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=e_(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},g_=function(){},h_=function(a,b){a_.call(this,a,b)},i_=function(){this.Ta=[];
this.Ca=[];this.Nd=[]},j_=function(a,b,c,d){var e=a.td[0]-b*Math.cos(g.vd(d))+b*Math.cos(g.vd(d+90)),f=a.td[1]-c*Math.sin(g.vd(d))+c*Math.sin(g.vd(d+90));
a.Ta.push(3);a.Ca.push(1);a.Nd.push(b,c,d,90,e,f);a.Hk=!1;a.td=[e,f]},Lna=function(a,b){for(var c=a.Nd,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Kna[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},k_=function(a,b,c,d){f_.call(this,a,b,c,d)},l_=function(a,b){this.g=a;
this.i=b},m_=function(a,b,c,d,e){g.Co.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Jna=function(a){var b=a.sj();
return b?b.width/(a.l?new g.yd(a.l,a.I):a.sj()).width:0},c_=function(a,b,c,d,e,f,k,l){this.u=a;
this.B=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},b_=function(a,b){this.F=a;
this.H=null==b?1:b},n_=function(a,b){a_.call(this,a,b)},o_=function(a,b,c,d){f_.call(this,a,b,c,d)},p_=function(a,b,c,d,e){m_.call(this,a,b,c,d,e);
this.g={};this.P=g.Rd&&!g.qd(526);this.O=new g.pn(this)},d_=function(a,b,c){a=a.M.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},q_=function(a,b,c,d){b=d_(a,"path",{d:Mna(b)});
c=new o_(b,a,c,d);a.o.ha().appendChild(c.ha())},Mna=function(a){var b=[];
Lna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},e_=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Nna++;c.setAttribute("id",d);a.g[b]=d;a.B.appendChild(c);return d},Ona=function(){r_||(r_=new g.Jg(400),r_.start());
return r_},s_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.G)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.G)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Zs(a.trackingParams));var k=(0,g.G)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.Wu=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.G)(u.loggingUrls||[],c);p.ll=g.Sb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.G)(n.impressionUrls||[],c);p.zD=(0,g.G)(n.hovercardShowUrls||[],c);p.Xc={itct:n.trackingParams};p.visualElement=g.Zs(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.im=!1,p.On=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.im=!1,p.On=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Sb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.im=!1;p.On="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var z=d(r.subscribedButtonText);if(r.subscribed){var C=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else C=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Sb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(z||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:C,unsubscribeText:z,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Sb(u,"urlEndpoint","url"),p.im=!0,p.On="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.ae)(k,function(l){return!!l});
return f},t_=function(a){g.RK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.B={};this.A=this.l=null;this.I=[];a=g.X(a);this.O=g.bz(a)||g.dz(a);this.lA=!0;this.D=0;this.F=new g.co;this.u=new g.hs(this);g.I(this,this.u);this.u.K(this.player,g.jE("creatorendscreen"),this.vE);this.u.K(this.player,"crx_creatorendscreen",this.wE);this.u.K(this.player,"resize",this.ib);this.u.K(window,"focus",this.gL);this.load();var b=g.Vd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.qf(this,function(){g.$d(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},u_=function(a){return a.player.getVideoData().Sb?"current":a.O?"new":"current"},v_=function(a){return"creator-endscreen-editor"===a},w_=function(a,b){g.zK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Pna(a);c=[];var d=new g.gE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({C:"div",G:"ytp-ce-shadow"}),g.DK(a.player,a.l.element,4),a.A=new g.mQ(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Qna(a,e);a.g[e.id]=f;a.B[e.id]=e;g.DK(a.player,f.element,4);var k=new g.gE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Rna(a,f,e)}g.wK(a.player,
c);a.ib()}},Pna=function(a){var b=g.ot(),c=g.pt();
c&&b&&a.i.visualElement&&g.at(c,b,[a.i.visualElement],void 0)},Qna=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={C:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.ll||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:S_(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.eo(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={C:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.ll||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:S_(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.eo(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-playlist-count",J:[{C:"div",
G:"ytp-ce-playlist-icon"},{C:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={C:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.ll||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",
J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{C:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.eo(a.F,b.title||"")},U:b.title},b.subscribeButton?{C:"div",G:"ytp-ce-subscribe-container",J:[{C:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{C:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{C:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:S_(b)}]};c=new g.W(c);var d=g.Id(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.L(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.Xc.itct}else e="endscreen",f=null;e=new g.cW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={C:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.ll||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",
J:[{C:"div",G:"ytp-ce-website-title",L:{dir:g.eo(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-website-metadata",U:b.metadata},{C:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:S_(b)},{C:"div",G:"ytp-ce-expanding-icon",L:f0(b.iconUrl)}]},c=new g.W(c)}b.g&&g.L(c.element,"ytp-ce-placeholder");return c},S_=function(a){if(a.Wu)var b=a.Wu.thumbnails;
return f0(b?b[b.length-1].url:null)},f0=function(a){return a?{style:"background-image: url("+a+")"}:{}},Rna=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.da("mouseenter",(0,g.y)(a.Oq,a,b,c));b.da("mouseleave",(0,g.y)(a.Hr,a,b,c));g.X(a.player).g||b.da("click",(0,g.y)(function(l){g.L(l.element,"ytp-ce-element-hover")},a,b));
b.da("click",(0,g.y)(a.ry,a,c));b.da("keypress",(0,g.y)(a.ry,a,c));b.da("focus",(0,g.y)(function(l,m){this.Oq(l,m)},a,b,c));
b.da("blur",(0,g.y)(function(l,m){this.Hr(l,m)},a,b,c));
b.da("touchstart",(0,g.y)(a.Oq,a,b,c));var f=g.Kd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.ko(b.element,"ytp-ce-element-hover");g.ko(b.element,"ytp-ce-force-expand")});
b.da("keydown",(0,g.y)(function(l,m){this.lA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.y)(function(l,m,n){this.D+=n;0<this.D?(g.L(l.element,"ytp-ce-force-expand"),g0(this,m.id,!0)):(g.ko(l.element,"ytp-ce-force-expand"),g.ko(l.element,"ytp-ce-element-hover"),g0(this,m.id,!1))},a,b,c);
a=(0,g.y)(function(l,m){m&&(l.da("blur",function(){LZ(m)&&this.lA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Kd("ytp-sb-subscribe",b.element));a(g.Kd("ytp-sb-unsubscribe",b.element));b.da("focus",d);b.da("blur",e)},g0=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.M(a.g[d].element,"ytp-ce-element-shadow-show",c)},h0=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||v_(g.X(a.player).playerStyle))c&&c();else{b=Sna(a,b);var e=0,f=!1,k=new g.N(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.qr(b[a],d)}},i0=function(a,b,c){h0(a,b.clickUrls,c);
(a=g.pt())&&b.im&&g.ct(a,b.visualElement)},Sna=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Tna(b[e],c));return d},Tna=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},j0=function(a){return g.La(a)&&a.length?a[0]:a},k0=function(a){var b=/.+/;
return g.v(a)&&null!=b&&null!=a&&a.match(b)?a:""},l0=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},m0=function(a){return g.v(a)?a:""},n0=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},o0=function(a,b){return"true"==a||"false"==a?"true"==a:b},p0=function(a,b){return g.v(a)?parseFloat(a):b},q0=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.sd(a,b,c);if(a>=b&&a<=c)return a}return e},Una=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.B)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},r0=function(a,b){if(null==a)return null;
if(g.Ma(a)){var c=[];(0,g.B)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},Vna=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.nh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},Wna=function(a){function b(c){return(0,g.ae)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},Xna=function(a){this.externalId=a},Yna=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},s0=function(a){if(!a)return null;
var b=g.Dc(m0(a.value));b=g.Ac(b);if(!b)return null;var c=n0(a.target,Zna,"current");return null==c?null:new Yna(b,c,o0(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},t0=function(a){return a.value?a.value:null},$na=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},coa=function(a){if(!a)return null;
var b=n0(a.type,aoa),c=n0(a.trigger,boa),d=j0(a.url);d=s0(d?d:null);a=j0(a.subscribeData);var e=a?a:null;e?(a=m0(e.external_user_id),e=m0(e.subscription_token),a=a&&e?new Xna(a):null):a=null;return b?new $na(b,c,d,a):null},u0=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},v0=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},w0=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Li=c;this.l=d;this.t=e;this.u=f;this.A=k;this.B=l;this.o=m;this.i=n;this.g=p},x0=function(a,b){if(!a)return null;
var c=p0(a.x,0),d=p0(a.y,0),e=p0(a.w,0),f=p0(a.h,0),k=Una(a.t),l=p0(a.d,0),m=p0(a.px,0),n=p0(a.py,0),p=p0(a.scaleSlope,1),r=p0(a.scaleSlopeX,p);p=p0(a.scaleSlopeY,p);var u=n0(a.scaleDimension,doa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},A0=function(a,b){var c=y0(b,z0(a,new g.qh(a.x,a.y,a.Li,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.sd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.sd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},z0=function(a,b,c){var d=a.A,e=a.B,f=a.g?a.g:"xy",k=u0(c,a.o,f);
a=v0(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.qh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},B0=function(a){return a?x0(a,function(b,c,d,e,f,k,l,m,n,p,r){return new w0(b,c,d,e,f,k,l,m,n,p,r)}):null},C0=function(a,b){this.g=a;
this.i=b||null},y0=function(a,b){var c=a.i?A0(a.i,new C0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.wd?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ga(c)&&(d.top+=c));return d},D0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){w0.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},eoa=function(a){if(!a)return null;
var b=p0(a.sx,0),c=p0(a.sy,0);return x0(a,function(d,e,f,k,l,m,n,p,r,u,z){return new D0(d,e,f,k,l,b,c,m,n,p,r,u,z)})},foa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=z},E0=function(a){if(!a)return null;
var b=l0(a.fgColor,"#1A1A1A"),c=l0(a.bgColor,"#FFF"),d=l0(a.borderColor,"#000"),e=q0(a.borderWidth,0,5,!1,0),f=q0(a.bgAlpha,0,1,!1,.8),k=l0(a.highlightFontColor,"#F2F2F2"),l=q0(a.highlightWidth,0,5,!1,3),m=m0(a.textAlign),n=q0(a.textSize,3.3,30.1,!0,3.6107),p=m0(a.fontWeight),r=Vna(a.padding),u=Wna(a.effects),z=q0(a.cornerRadius,0,10,!0,0);a=j0(a.gradient);if(a=a?a:null){var C=q0(a.x1,0,100,!0,0),E=q0(a.y1,0,100,!0,0),F=q0(a.x2,0,100,!0,100),K=q0(a.y2,0,100,!0,100),Y=l0(a.color1,"#FFF"),Ca=l0(a.color2,
"#000");a=new goa(C,E,F,K,Y,Ca,q0(a.opacity1,0,100,!0,100),q0(a.opacity2,0,100,!0,0))}else a=null;return new foa(b,c,d,e,f,k,l,m,n,p,r,u,z,a)},goa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.B=k;this.D=l},hoa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},joa=function(a){if(!a)return null;
var b=n0(a.type,ioa,"rect"),c=r0(a.rectRegion,B0),d=r0(a.anchoredRegion,eoa);a=r0(a.shapelessRegion,B0);return new hoa(b,c,d,a)},F0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},koa=function(a,b){this.i=a;
this.g=b},loa=function(a,b){this.state=a;
this.ref=b},G0=function(a){if(!a)return null;
var b=n0(a.state,moa);a=k0(a.ref);return b?new loa(b,a):null},noa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},ooa=function(a){if(!a)return null;
var b=r0(a.condition,G0),c=r0(a.notCondition,G0),d=o0(a.show_delay,!1);a=o0(a.hide_delay,!1);return b||c?new noa(b,c,d,a):null},poa=function(a,b,c){(0,g.B)(a.g,g.Ra(b,!1),c);
(0,g.B)(a.l,g.Ra(b,!0),c)},H0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.B=l||[];this.i=m;this.A=n;this.u=p;this.data=r;this.g=u;this.itct=z},soa=function(a){if(!a)return null;
var b=k0(a.id),c=k0(a.author),d=n0(a.type,qoa),e=n0(a.style,I0),f=m0(j0(a.TEXT)),k=m0(a.data);k=0!=k.length?JSON.parse(k):{};var l=j0(a.segment);var m=l?l:null;m?(k0(m.timeRelative),l=k0(m.spaceRelative),l=(m=r0(m.movingRegion,joa))?new koa(l,m):null):l=null;m=r0(a.action,coa);var n=r0(a.trigger,ooa),p=j0(a.appearance);(p=E0(p?p:null))||(p=E0({}));var r=n0(a.coordinate_system,roa,"video_relative"),u=o0(a.closeable,!0),z=m0(a.log_data);a=m0(a.itct);return b&&d?new H0(b,c,d,e,f,l,m,n,p,r,u,k,z,a):null},
K0=function(a){return J0(a,function(b){return"click"==b.trigger})},J0=function(a,b){return(0,g.Sj)(a.l,b,void 0)},toa=function(a,b,c){(0,g.B)(a.l,b,c)},uoa=function(a,b){return g.Xa(a.l,b,void 0)},L0=function(a,b,c){(0,g.B)(a.B,b,c)},voa=function(a,b){(0,g.G)(a.B,b,void 0)},N0=function(a){return(a=M0(a))?F0(a):null},M0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},O0=function(a,b){var c=N0(a);
return c&&b?v0(b,c.i,c.g?c.g:"xy"):1},Q0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;poa(b,function(d,e){var f=P0(e.state,e.ref);this.i.subscribe(f,(0,g.y)(this.o,this,f,d));this.g[f]=d},this)},P0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},R0=function(){this.g=!1;
this.u=this.i=null},S0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new p_(b,c,void 0,void 0,void 0),a.i=b,a.i.Pp(),a.u=g.Ud("DIV"),a.u.appendChild(a.i.ha()));
return a.i},T0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Kb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},U0=function(a,b){var c=g.Bo(g.Ao.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},woa=function(a,b){var c=U0(a,T0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=U0(a,T0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},T0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=U0(a,T0("feComposite",{"in":c,in2:b,operator:"in"}));return U0(a,T0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},xoa=function(a,b){var c=U0(a,T0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=U0(a,T0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=U0(a,T0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=U0(a,T0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=U0(a,T0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=U0(a,T0("feComposite",{operator:"out","in":c,in2:d}));return U0(a,T0("feComposite",{operator:"over","in":b,in2:c}))},yoa=function(a,b){return b},zoa=function(a){var b=
T0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.B)(a,function(d){a:{switch(d){case "bevel":d=woa;break a;case "dropshadow":d=xoa;break a}d=yoa}c=d(b,c)});
return b},Aoa=function(a){a=(0,g.ae)(a,function(b){return b in V0});
g.qb(a,function(b,c){return V0[b]-V0[c]});
return a},Boa=function(a){return g.Xa(a,function(b){return"dropshadow"==b})?new g.nh(0,7,7,0):new g.nh(0,0,0,0)},W0=function(a,b,c){var d=new i_;
d.moveTo(a.left+b+c,a.top+c);d.ec(a.left+a.width-b-c,a.top+c);j_(d,b,b,-90);d.ec(a.left+a.width-c,a.top+a.height-b-c);j_(d,b,b,0);d.ec(a.left+b+c,a.top+a.height-c);j_(d,b,b,90);d.ec(a.left+c,a.top+b+c);j_(d,b,b,180);d.close();return d},X0=function(a,b,c,d){var e=a.u;
e?a=new c_(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.B,e.D):(b=a.g,a=new b_(a.bgColor,d?Math.max(b,.9):b));return a},Y0=function(a,b){var c=g.rh(a),d=Boa(b);
g.Oa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.qh(c.left,c.top,c.right-c.left,c.bottom-c.top)},Z0=function(a,b,c){if(c.length&&(b=g.Id(document,"g",void 0,b),b.length)){var d=Aoa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=zoa(d),a=0<d.childNodes.length?e_(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},$0=function(){R0.call(this);
this.o=0},Coa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},a1=function(){R0.apply(this,arguments)},b1=function(){R0.apply(this,arguments)},c1=function(){$0.apply(this,arguments)},d1=function(a,b,c,d,e){g.H.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Y=e;this.F=!1;this.ba=new XZ(this);g.I(this,this.ba);this.M=this.u=this.B=this.O=this.i=null;this.V=!1;this.aa=this.H=this.I=null;this.Wm=new g.Jl(this.ZC,100,this);g.I(this,this.Wm);this.D=new g.N(this.ew,500,this);g.I(this,this.D);this.P=this.l=this.o=null},Doa=function(a,b){var c=(0,g.y)(function(d,e,f){e=f?e1(this,e,(0,g.y)(f,this)):e1(this,e);
this.ba.da(b,d,e)},a);
c("mouseover","G",a.fx);c("mouseout","F",a.tg);c("click","D");c("touchend","D")},Eoa=function(a){if(a.g.u){if(J0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Ud("DIV","annotation-close-button"),g.Xh(a.o,!1),g.Wp(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.ba.da(b,"click",e1(a,"E",c));a.ba.da(b,"touchend",e1(a,"E",c))}},e1=function(a,b,c){return(0,g.y)(function(d){if(this.Y)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Xh(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.je(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Xh(e,
!0)}}e=JZ(d.target);d=new g.wd(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.N(b,this.g)},a)},h1=function(a){if(a.i||a.l){var b=N0(a.g);
if(b){var c=f1(a);if(a.i){b=A0(b,c);var d=g.oK(a.A).getVideoContentRect();g.Vh(a.i,b.width,b.height);g.Kh(a.i,b.left,b.top);a.O=new g.qh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=N0(a.g))&&d?u0(d,e.o,e.g?e.g:"xy"):1;var f=O0(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.nh(d,d,d,d));d=new g.nh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.B&&(a.B.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.oK(a.A).getVideoContentRect();var p=g.uK(a.A);g.sh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=g1(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Vh(a.u,f.width,f.height);g.Kh(a.u,f.left,f.top)}a.o&&(r?b=new g.wd(r.left+
r.width-23-18,a.V?r.top+2:r.top+r.height-18-2):(r=g1(a,18,b,d,e),b=new g.wd(r.left,r.top),g.Vh(a.o,r.width,r.height)),g.Kh(a.o,b));a.M=new g.qh(a.O.left+r.left,a.O.top+r.top,r.width,r.height);a.I=a.ba.da(g.oK(a.A),"mousemove",a.kF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.yd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.qh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.qh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Vh(a.u,
r.width,r.height),g.Kh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Kh(a.o,r&&e?new g.wd(b.width-9,-9):r?new g.wd(b.width-9,45<b.height?9:b.height-9):e?new g.wd(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.wd(45<b.width?b.width-9-18:-9,b.height-9):new g.wd(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.oK(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
O0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Kd("annotation-link-icon",a))?LZ(b):!1;e=(d=g.Kd("annotation-close-button",a))?LZ(d):!1;r&&g.Xh(b,!1);e&&g.Xh(d,!1);m=f="";if(n=g.Kd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Dna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Xh(d,!0);r&&g.Xh(b,!0)}}}},g1=function(a,b,c,d,e){var f=0<e;
b=new g.qh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.L(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.L(a.i,"annotation-extend-up"),a.V=!0);return b},i1=function(a){return"label"!=a.g.style||a.l.g},f1=function(a){var b=g.oK(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.oK(a.A).getPlayerSize();b=new g.qh(-b.left,-b.top,c.width,c.height)}else b=new g.qh(0,0,b.width,b.height);return new C0(b,a.P?N0(a.P):null)},j1=function(a,b){return b?new g.qh(a.x+b.left,a.y+b.top,b.width,b.height):null},k1=function(a,b,c){g.H.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Foa(b,a)},Foa=function(a,b){voa(a,function(c){return new Q0(a.id,c,b)})},l1=function(a){a.i.unsubscribe("resize",a.bx,a);
a.i.unsubscribe("onVideoAreaChange",a.Sy,a)},m1=function(a){a.g&&(a.g.stop(),a.g=null)},n1=function(a,b,c){$Z.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.o=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=s0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},o1=function(a,b,c){$Z.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=s0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=s0({target:"current",value:a});this.I=b.signin_title||null;this.H=b.signin_message||null},p1=function(a,b,c){o1.call(this,a,b,c);
this.F=b.ypc_flow_type;this.B=b.innertube_request_params},q1=function(a,b,c){$Z.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=s0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},r1=function(a,b,c){$Z.call(this,a,b,c);
this.B=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=s0({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},s1=function(a,b,c){o1.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new Goa(a[b]))},Goa=function(a){this.merchant=g.dd(a.merchant);
this.price=g.dd(a.price)},t1=function(a,b,c){o1.call(this,a,b,c);
this.O=b.ypc_item_type;this.F=b.ypc_item_id;this.B=b.ypc_flow_type},u1=function(a,b,c){$Z.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=s0({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},v1=function(a,b,c){$Z.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.B=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=s0({target:b.target||"new",value:b.url})},Hoa=function(a){this.g=a;
this.i={}},Ioa=function(a){var b={};
b=(b["iv-event"]=1,b);g.tK(a.g,"iv",b,void 0)},z1=function(a,b,c,d){if(b){var e=w1(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=x1(a,"cta_annotation_shown",e,c);y1(a,e,Joa(b,d))}},A1=function(a,b,c,d,e,f){if(b){var k=w1(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=x1(a,"cta_annotation_clicked",k,e);y1(a,k,b,c,f)}},B1=function(a,b){if(b){var c=w1(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=x1(a,"cta_annotation_closed",c);y1(a,c,d)}},Joa=function(a,b){return b?(0,g.G)(a,g.Ra(function(c,d){return g.sn(d,c)},b)):a},x1=function(a,b,c,d){d=d?g.gb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.R(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.ku){if((b=a.ku[b])&&g.nv(b)){a=g.Zc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.nn){b=g.Fq(a.nn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},y1=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.B)(c||[],function(n){f++;
g.qr(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.tK(a.g,"iv",b,m)},w1=function(a,b){var c={};
if(b){var d=new g.gn(b);(0,g.B)(d.Dd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},C1=function(a,b,c,d,e){e=w1(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;y1(a,e,d)},D1=function(a,b,c,d){c&&(c=w1(a,c),c["iv-event"]=b,y1(a,c,d))},Koa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.sb=c;this.videoData=d;this.logger=e;this.Z=f;this.i=k},E1=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.co},Loa=function(a,b){var c=[];
(0,g.B)(b.choices,function(k){c.push({C:"li",G:b.B+"-"+k.index.toString(),J:[{C:"label",J:[{C:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.B+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{C:"span",G:"iv-card-poll-choice-text",J:[{C:"span",G:"iv-card-poll-choice-percent"},F1(this,"span",void 0,k.desc)]}]},{C:"div",G:"iv-card-poll-result",J:[{C:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={C:"ul",L:{role:"radiogroup"},J:c},e={};b.o&&(e["aria-label"]=g.BN("$POLL_TITLE - \u6295\u7968\u3059\u308b\u306b\u306f\u30ed\u30b0\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{C:"div",G:"iv-card-content",J:[F1(a,"h2",e,b.title),{C:"form",J:[{C:"fieldset",J:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({C:"div",W:["iv-card-sign-in"],J:[{C:"h2",U:"\u30a2\u30f3\u30b1\u30fc\u30c8\u306b\u53c2\u52a0\u3059\u308b\u306b\u306f"},
{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:t0(b.o)},J:[{C:"span",W:["iv-button-content"],U:"\u30ed\u30b0\u30a4\u30f3"}]}]}));f=new g.W({C:"div",W:f,J:d});d=f.element;G1(b,d);Ina(a.g.g,d,g.Ra(a.B,b),a);(0,g.B)(g.Jd("iv-card-poll-choice-input",d),function(k){this.g.g.da(k,"focus",g.Ra(this.l,!0));this.g.g.da(k,"blur",g.Ra(this.l,!1))},a);
b.o&&(d=g.Kd("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Xc,b.l,b.i.click,5));return f},K1=function(a,b,c,d){var e=b.displayDomain?{C:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=H1(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{C:"a",G:"iv-click-target",L:{href:t0(b.url)},J:[I1(b.imageUrl,e),{C:"div",G:"iv-card-content",J:[F1(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({C:"div",W:["iv-card-sign-in"],J:[F1(a,"h2",void 0,b.I||""),{C:"p",U:b.H},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:t0(b.g)},J:[F1(a,"span","iv-button-content","\u30ed\u30b0\u30a4\u30f3")]}]});k=new g.W({C:"div",W:k,J:e});J1(a,k,b,c,d);return k},
M1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.B&&b.o?{C:"span",W:d,L:e,U:b.o}:"";c={C:"div",W:["iv-card",c],J:[{C:"a",G:"iv-click-target",L:{href:t0(b.url)},J:[I1(b.F,d?{C:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{C:"div",G:"iv-card-content",J:[{C:"h2",G:"iv-card-primary-link",U:b.title},L1(a,b)]}]}]};c=new g.W(c);J1(a,c,b);return c},N1=function(a,b){return b.customMessage?F1(a,"div","iv-card-message",
b.customMessage):""},I1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{C:"div",G:"iv-card-image",L:{style:c},J:d}},L1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.B)(b.metaInfo,function(d){c.push(F1(this,"li","",d))},a);
return{C:"ul",G:"iv-card-meta-info",J:c}},F1=function(a,b,c,d){c?g.v(c)?c={"class":c}:g.La(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.eo(a.i,d);return{C:b,L:c,U:d}},H1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.eo(a.i,b.customMessage);var e=[{C:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({C:"span",G:"iv-card-link-icon"}));return{C:"div",W:c,L:d,J:e}},G1=function(a,b){var c=0;
(0,g.B)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Kd(a.B+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.M(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.Kd("iv-card-poll-choice-percent",f);g.ee(l,g.BN("$PERCENT%",{PERCENT:k}));f=g.Kd("iv-card-poll-result-bar",f);g.Ch(f,"transform","scaleX("+e.toFixed(2)+")")}g.M(b,"iv-card-poll-voted",null!=a.g);g.M(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},O1=function(a,b,c,d){d?(c&&a.g.videoData.ra||a.g.Z.pauseVideo(),a.g.Z.isFullscreen()&&a.g.Z.toggleFullscreen(),A1(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.pt())&&g.ct(a,b.A)):b.url&&a.u(b.url,b.id,b.Xc,b.l,b.i.click||[],5)},J1=function(a,b,c,d,e){c.g&&P1(a,g.Jd("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&P1(a,g.Jd("iv-click-target",b.element),c,c.url,d)},P1=function(a,b,c,d,e){(0,g.B)(b,function(f){if(e){var k=(0,g.y)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.da(f,"click",k)}else d&&this.o(f,d,c.id,c.Xc,c.l,c.i.click,5)},a)},Q1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},S1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=R1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},R1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Moa=function(a){a=t0(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!S1(a))||(b=g.Vg(g.Ug(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.Dq(a);if(!b||!b.v)return null;if(b=b.t)return Q1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.Bq(a[1]))&&a.t?Q1(a.t):-1},T1=function(a){a=t0(a);
a=a.replace(/https?:\/\//g,"");return S1(a)?(a=g.Dq(a))&&a.v?a.v:null:null},Noa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},U1=function(a,b){return b?b:S1(a)?"current":"new"},V1=function(a,b){g.H.call(this);
this.Ba=a;this.context=b;this.Vs=!1;this.X=0},Ooa=function(a){return(0,g.D)()-a.X},Poa=function(a,b,c,d,e,f){var k=t0(b);
if(k){var l=U1(k,b.target),m=(0,g.y)(function(){b.g&&this.context.Z.pauseVideo();var p=this.context.videoData.Sb||!1,r=g.Dq(k||"");p&&r&&(r.v||r.list)?g.iY(this.context.Z.app,r.v,c,r.list,!1,void 0,void 0):g.KL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Ooa(a);A1(a.context.logger,d,m,n,e,f);S1(k)||(a=g.pt(),d=c.itct,a&&d&&g.ct(a,g.Zs(d)))}},Y1=function(a,b,c){V1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.V=this.xa=this.u=this.va=!1;this.aa=null;this.M=new g.N(g.Ia,c.sb.dd?4E3:3E3);g.I(this,this.M);this.ka=new g.N(g.Ia);g.I(this,this.ka);this.A=new E1(c,(0,g.y)(this.Ai,this),(0,g.y)(this.tm,this));this.F=new g.W({C:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{C:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{C:"span",G:"iv-drawer-header-text"},{C:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"\u30ab\u30fc\u30c9\u3092\u9589\u3058\u308b",
tabindex:"0"}}]},{C:"div",G:"iv-drawer-content"}]});g.I(this,this.F);this.B=this.F.element;this.wa=new g.mQ(this.F,330);g.I(this,this.wa);this.ya=g.Kd("iv-drawer-header-text",this.B);this.o=g.Kd("iv-drawer-content",this.B);this.l=[];this.na=this.P=this.D=this.Y=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&W1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.u)&&X1(d)});
this.O=this.H=this.ca=null},Toa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&Z1[c]){c=new Z1[c](b.id,b.data,b.g);if(!a.va){g.jo(a.ha(),["html5-stop-propagation","iv-drawer-manager"]);g.DK(a.i,a.B,5);Qoa(a);a.P=g.Kd("ytp-cards-button",a.i.getRootNode());var d=g.Kd("iv-drawer-close-button",a.B);a.na=d;a.va=!0}$1(a,c.id);var e=Roa(a,c);if(e){d={Gb:c,Wo:e.element,Cw:!1};var f=Soa(a,d);g.kb(a.l,f,0,d);e.g(a.o,f);a.ul();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Ra(a.KL,d)):(e=1E3*a.context.Z.getCurrentTime(),5E3>e&&e>c.startMs&&a.Rz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Ra(a.Rz,d)),a2(a))}}},Uoa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){W1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){X1(a)});
var c=b.data.headerText;g.ee(a.ya,c);a.P&&a.P.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.ca=g.Zs(b.data.trackingParams);a.O=g.Zs(b.data.closeTrackingParams);a.H=g.Zs(b.data.iconTrackingParams)},$1=function(a,b){var c=Voa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Gb.id),g.$d(c.Wo),g.cb(a.l,c),a.ul(),a2(a))},W1=function(a,b,c,d){if(!a.u){a.wa.show();
a.Y=new g.N(function(){g.L(a.context.Z.getRootNode(),"ytp-iv-drawer-open")},0);
a.Y.start();a.aa=g.Vr(a.o,"mousewheel",(0,g.y)(a.LE,a));a.u=!0;a.X=(0,g.D)();C1(a.context.logger,a.R,7,void 0,d&&d.Gb?d.Gb.l:void 0);var e=g.pt();e&&a.ca&&a.O&&YZ(e,[a.ca,a.O]);var f={TRIGGER_TYPE:b};(0,g.B)(a.l,function(k){k.Cw||(k.Cw=!0,z1(a.context.logger,k.Gb.l,k.Gb.i.BD,f));e&&YZ(e,[k.Gb.A])});
IZ(a.i);c&&(a.D=new g.N(function(){a.ia=a.P;a.na.focus()},330),a.D.start())}},X1=function(a){a.u&&(a.wa.hide(),g.Wr(a.aa),a.aa=null,g.ko(a.context.Z.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,IZ(a.i),a.D&&a.D.stop(),a.D=new g.N(function(){a.ia&&(a.ia.focus(),a.ia=null)},330),a.D.start())},Qoa=function(a){var b=g.Kd("iv-drawer-close-button",a.B);
a.context.g.da(b,"click",a.dC,a);a.context.g.da(a.o,"touchend",function(){a.M.start()});
a.context.g.da(a.o,"scroll",a.nC,a);a.context.i.subscribe("onHideControls",function(){a.V=!0});
a.context.i.subscribe("onShowControls",function(){a.V=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.V=g.io(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.fq("iv-button-shown",a.TD,a));a.I.push(g.fq("iv-button-hidden",a.SD,a));a.I.push(g.fq("iv-teaser-shown",a.WD,a));a.I.push(g.fq("iv-teaser-hidden",a.VD,a));a.I.push(g.fq("iv-teaser-clicked",a.UD,a))},Roa=function(a,b){switch(b.type){case "simple":return K1(a.A,b);
case "collaborator":var c=a.A,d={C:"div",W:["iv-card","iv-card-channel"],J:[{C:"a",W:["iv-click-target"],L:{href:t0(b.url),"data-ytid":b.channelId},J:[I1(b.o),{C:"div",G:"iv-card-content",J:[N1(c,b),{C:"h2",G:"iv-card-primary-link",U:b.title},L1(c,b)]}]}]};d=new g.W(d);J1(c,d,b);return d;case "donation":return c=a.A,d=(0,g.y)(c.A,c,b),K1(c,b,d,d);case "episode":return M1(a.A,b,"iv-card-episode");case "movie":return M1(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={C:"div",W:["iv-card","iv-card-playlist"],
J:[{C:"a",G:"iv-click-target",L:{href:t0(b.url)},J:[I1(b.o,{C:"div",G:"iv-card-image-overlay",J:[{C:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{C:"div",G:"iv-card-content",J:[N1(c,b),F1(c,"h2","iv-card-primary-link",b.title),L1(c,b)]}]}]},d=new g.W(d),J1(c,d,b),d;case "poll":return Loa(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=H1(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],k=[],e.price&&
k.push({C:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({C:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={C:"div",J:k});d={C:"div",W:d,L:{tabindex:"0"},J:[{C:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:t0(b.url),"aria-hidden":"true",tabindex:"-1"}},{C:"div",G:"iv-card-content",J:[b.sponsored?{C:"div",G:"iv-card-sponsored",J:["\u30b9\u30dd\u30f3\u30b5\u30fc\u63d0\u4f9b",{C:"div",G:"iv-ad-info-container",J:[{C:"div",G:"iv-ad-info",
U:"{{adInfo}}"},{C:"div",G:"iv-ad-info-icon-container",J:[{C:"div",G:"iv-ad-info-icon"},{C:"div",G:"iv-ad-info-callout"}]}]}]}:"",{C:"a",G:"iv-click-target",L:{href:t0(b.url)},J:[F1(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.Vd("span");g.ee(f,"\u3053\u306e\u52d5\u753b\u306b\u95a2\u9023\u3057\u3066\u3044\u308b\u3068\u601d\u308f\u308c\u308b\u5546\u54c1\u3092\u8868\u793a\u3057\u3066\u3044\u307e\u3059\u3002Google \u306f\u8ca9\u58f2\u8005\u304b\u3089\u652f\u6255\u3044\u3092\u53d7\u3051\u3066\u3044\u308b\u3053\u3068\u304c\u3042\u308a\u307e\u3059\u3002");
d.nb(f,"adInfo");J1(c,d,b);return d;case "tip":return c=a.A,d=(0,g.y)(c.D,c,b),K1(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{C:"span",W:["yt-badge","yt-badge-live"],U:"\u30e9\u30a4\u30d6\u914d\u4fe1\u4e2d"}:"",d={C:"div",W:["iv-card","iv-card-video"],J:[{C:"a",G:"iv-click-target",L:{href:t0(b.url)},J:[I1(b.o,b.videoDuration?{C:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{C:"div",G:"iv-card-content",J:[N1(c,b),F1(c,"h2","iv-card-primary-link",b.title),L1(c,b),d]}]}]},d=new g.W(d),
J1(c,d,b),d}return null},Soa=function(a,b){if(0==a.l.length)return 0;
var c=g.Ya(a.l,function(d){return b.Gb.startMs>d.Gb.startMs||b.Gb.startMs==d.Gb.startMs&&b.Gb.timestamp>=d.Gb.timestamp?!0:!1});
return-1==c?0:c+1},Woa=function(a){return a.g?"productListing"==a.g.Gb.type:(0,g.kj)(a.l,function(b){return"productListing"==b.Gb.type})},a2=function(a){g.M(a.i.getRootNode(),"ytp-cards-shopping-active",Woa(a))},b2=function(a,b){if(a.F.Fa()){var c=new TZ([0,
a.o.scrollTop],[0,b.Wo.offsetTop],600,Hna);a.context.l.da(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.da(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.aD(a.F,!0),a.o.scrollTop=b.Wo.offsetTop,g.aD(a.F,!1)},c2=function(a){return a.g&&a.g.Gb?a.g.Gb:a.l[0]&&a.l[0].Gb?a.l[0].Gb:null},Voa=function(a,b){return g.Xa(a.l,function(c){return c.Gb.id==b})},d2=function(a,b,c){V1.call(this,a,b);
this.annotation=c;this.isActive=!1},Xoa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},e2=function(a,b,c){d2.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.B=this.A=null},f2=function(a,b,c){d2.call(this,a,b,c);
this.F=this.u=this.H=!1;this.B=5E3;this.o=null;this.D=g.Ud("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.N(function(){this.g.setAttribute("aria-hidden",!0);g.Xh(this.l,!1);g.Xh(this.i,!0)},700,this);
g.I(this,this.A)},Yoa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.B=b.collapse_delay_ms||a.B;var d=["iv-promo","iv-promo-inactive"];a.ha().setAttribute("aria-hidden",!0);a.ha().setAttribute("aria-label","\u30d7\u30ed\u30e2\u30fc\u30b7\u30e7\u30f3");a.ha().tabIndex=0;var e=a.annotation.Hb(),f=b.image_url;if(f){var k=g.Ud("DIV",["iv-promo-img","iv-click-target"]);f=g.Ud("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=
g.Ud("SPAN","iv-promo-video-duration",b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Ud("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Ai(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.Ud("A","iv-promo-txt"),g.Wc(f,t0(e)),a.g=f):a.g=g.Ud("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Ud("P",null,g.Ud("STRONG",null,b.text_line_1));var m=g.Ud("P",null,g.Ud("SPAN","iv-promo-link",b.text_line_2));
if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.sb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Ud("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Ud("BUTTON",["iv-button","iv-promo-button"],g.Ud("SPAN","iv-button-content",f));var p=g.Ud("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Ai(a.ha(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.L(a.g,"iv-click-target");e&&a.Ai(a.g,e,a.annotation.id,
b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=g.Ud("P",null,g.Ud("SPAN",null,b.text_line_1)),m=g.Ud("P",null,g.Ud("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Ud("SPAN",["yt-badge","iv-promo-badge-live"],"\u30e9\u30a4\u30d6\u914d\u4fe1\u4e2d")),g.L(a.g,"iv-click-target"),e&&a.Ai(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Ud("DIV",
"iv-promo-actions");a.i=g.Ud("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="\u62e1\u5927";a.context.g.da(a.i,"click",g.Ra(a.Rp,5E3),a);c.appendChild(a.i);g.Xh(a.i,!1);a.context.g.da(a.ha(),"mouseover",a.bD,a);a.context.g.da(a.ha(),"mouseout",a.aD,a);a.context.g.da(a.ha(),"touchend",g.Ra(a.Rp,5E3),a);a.l=g.Ud("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="\u9589\u3058\u308b";a.context.g.da(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.TC:a.SC,a);c.appendChild(a.l);g.jo(a.ha(),
d);k&&(a.ha().appendChild(k),n&&k.appendChild(n));a.ha().appendChild(a.D);a.ha().appendChild(c)},g2=function(a){a.u||a.F||a.o||(g.L(a.ha(),"iv-promo-collapsed"),a.u=!0,a.A.start())},h2=function(a){a.A.stop();
a.u&&(g.lo(a.ha(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Xh(a.i,!1),g.Xh(a.l,!0))},j2=function(a,b){a.o||(a.o=g.Kg(function(){i2(this);
g2(this)},b,a))},i2=function(a){a.o&&(g.w.clearTimeout(a.o),a.o=null)},k2=function(a){g.RK.call(this,a);
this.I=!1;this.H=0;this.i={};this.O={};this.D=new Hoa(a);this.A=new g.hs(this);g.I(this,this.A);this.B=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.y)(this.N,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.y)(this.N,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.y)(this.N,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.y)(this.N,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.y)(this.N,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.uI,this);this.subscribe("onShowControls",this.tK,this);this.subscribe("presentingplayerstatechange",this.CJ,this);this.subscribe("resize",this.Ir,this);this.subscribe("G",this.tE,this);this.subscribe("F",this.tg,this);this.subscribe("D",this.tH,this);this.subscribe("E",this.WH,this);g.X(this.player).I.subscribe("vast_info_card_add",this.Ry,this);this.R=new g.hs(this);g.I(this,this.R);this.R.K(this.player,g.jE("annotations_module"),this.rE);this.R.K(this.player,
"crx_annotations_module",this.sE);this.P=g.Ud("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.V=g.Ud("DIV","video-custom-annotations");this.u=new g.W({C:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.DK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({C:"div",W:["ytp-iv-video-content"]});g.I(this,this.o);g.Xd(this.o.element,g.Ud("DIV","video-annotations",this.P,this.V));this.F=this.g=null;this.M=[];Zoa(this)&&this.load();var b=g.Vd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.qf(this,function(){g.$d(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},l2=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Zoa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Nf||a.Nf)&&!a.PA||null!==b.I.get(a.videoId)},m2=function(a,b,c){a.I=!0;
a.B=g.Wq(b,c)},n2=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(n2(a,e))}return c},o2=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},apa=function(a,b){var c=$oa(a,b);
if(!c&&"marker"!=b.type)return null;L0(b,function(e){e=(0,g.y)(this.RK,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new k1(a.wa,b,c);g.I(d,c);return d},bpa=function(a,b){var c=g.Ud("DIV",["annotation",
"annotation-type-custom"]);g.Xh(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).Bh)break;a.u.element.appendChild(c);d=new e2(c,p2(a),b);break;case "promotion":g.DK(a.player,c,4),d=new f2(c,p2(a),b)}d&&d.In();return d},cpa=function(a){var b=a.player.getVideoData();
if(b.Bd){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Cc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Cc.gaming="1");e.Wc=(0,g.y)(function(f,k,l){o2(this,f,k)||(f=g.Qq(l)&&l.responseXML?l.responseXML:null)&&q2(this,f)},a,a.H,b.videoId);
g.tq()&&(e.Wc=r2(a,e.Wc));e.rb={ic_only:"1"};s2(e,d);a.I=!0;g.Wq(b.Bd,e)}}},s2=function(a,b){a.method="POST";
a.rb=a.rb||{};b.zl&&(a.rb.ic_coll=b.zl);b.Al&&(a.rb.ic_xml=b.Al);b.Js&&(a.rb.ic_track=b.Js)},dpa=function(a){var b=new g.W({C:"div"});
g.Xh(b.element,!1);var c=new Y1(a.player,b.element,p2(a));g.I(c,b);b.g(a.u.element);c.In();return c},p2=function(a){if(!a.F){var b=new XZ(a);
g.I(a,b);var c=new g.pn(a);g.I(a,c);a.F=new Koa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.wa)}return a.F},q2=function(a,b){var c=!1;
epa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=n2(a,d[e]),k=null;try{k=soa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=bpa(a,k))g.I(a,f),a.O[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=dpa(a),g.I(a,a.g)),"card"==k.type?Toa(a.g,k):Uoa(a.g,k),c=!0;else if(f=apa(a,k))g.I(a,f),a.i[k.id]=f}}c&&(IZ(a.player),a.Ir());g.Kb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.P=m.annotation)}},a)},epa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.pt();
if(b){var c=g.ot();c&&g.at(b,c,[g.Zs(a)])}}},fpa=function(a,b,c,d){d?t2(a,b,c):u2(a,b,c)},u2=function(a,b,c){if(b=a.i[b])m1(b),c&&c.i?(a=(0,g.y)(a.dw,a,b),b.g=new g.N(a,2E3),b.g.start()):a.dw(b)},t2=function(a,b,c){if(b=a.i[b])m1(b),c&&c.o?(a=(0,g.y)(a.dA,a,b),b.g=new g.N(a,2E3),b.g.start()):a.dA(b)},v2=function(a,b){var c=a.player.getVideoData();
if(!c.ol)return!1;var d=t0(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!S1(d))return!1;d=g.Dq(d);return d.list||d.p?!1:(d=T1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},$oa=function(a,b){if(gpa(b)){var c=b.u||J0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new d1(b,(0,g.y)(a.P.appendChild,a.P),a.player,a.wa,c)}return null},gpa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in I0)if(a.style==I0[b])return!0;return!1},w2=function(a,b,c,d){a.N(P0(b,d),c,d)},r2=function(a,b){return(0,g.y)(function(){if(!this.ea()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.M.push(g.rq(b))}},a)};
g.iK.prototype.xi=g.ca(14,function(a,b){var c=g.jK(this).l;c&&c.xi(a,b)});
g.Co.prototype.Pp=g.ca(0,function(){this.i=this.M.createElement("DIV")});
var Ana=/[^\d]+$/,Bna={cm:1,"in":1,mm:1,pc:1,pt:1},Cna={em:1,ex:1},NZ={},OZ=null;g.A(SZ,g.tf);g.A(TZ,g.no);g.h=TZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;PZ(this);this.startTime=a=(0,g.D)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Qd("play");-1==this.g&&this.Qd("resume");this.g=1;var b=g.Qa(this);b in NZ||(NZ[b]=this);QZ();RZ(this,a);return!0};
g.h.stop=function(a){PZ(this);this.g=0;a&&(this.progress=1);UZ(this,this.progress);this.Qd("stop");this.l()};
g.h.pause=function(){1==this.g&&(PZ(this),this.g=-1,this.Qd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Qd("destroy");TZ.Ha.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ar=function(){this.Qd("animate")};
g.h.Qd=function(a){this.dispatchEvent(new SZ(a,this))};
g.A(VZ,TZ);VZ.prototype.u=g.Ia;VZ.prototype.Ar=function(){this.u();VZ.Ha.Ar.call(this)};
VZ.prototype.l=function(){this.u();VZ.Ha.l.call(this)};
VZ.prototype.o=function(){this.u();VZ.Ha.o.call(this)};
g.A(WZ,VZ);WZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(XZ,g.H);XZ.prototype.da=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.Vr(a,b,c);this.g.push(a);return a};
XZ.prototype.wm=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.es(a,b,c);this.g.push(a);return a};
XZ.prototype.Na=function(a){g.Wr(a);g.cb(this.g,a)};
XZ.prototype.T=function(){g.Wr(this.g);this.g.length=0;g.H.prototype.T.call(this)};g.A(a_,g.Uf);g.h=a_.prototype;g.h.Kp=null;g.h.Cj=null;g.h.ha=function(){return this.Cj};
g.h.addEventListener=function(a,b,c,d){g.Df(this.Cj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Of(this.Cj,a,b,c,d)};
g.h.T=function(){a_.Ha.T.call(this);var a=this.Cj;if(a)if(g.wf(a))a.he&&g.Af(a.he);else if(a=g.Hf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Pf(d[e])&&++b}};g.A(f_,a_);f_.prototype.fill=null;g.A(h_,a_);i_.prototype.ze=null;i_.prototype.td=null;i_.prototype.Hk=!0;var Kna=[2,2,6,6,0];g.h=i_.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Nd.length=0;delete this.ze;delete this.td;delete this.Hk;return this};
g.h.moveTo=function(a,b){0==g.Va(this.Ta)?this.Nd.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Nd.push(a,b);this.td=this.ze=[a,b];return this};
g.h.ec=function(a){var b=g.Va(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Nd.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.td=[c,d]};
g.h.close=function(){var a=g.Va(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.td=this.ze);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Nd=this.Nd.concat();a.ze=this.ze&&this.ze.concat();a.td=this.td&&this.td.concat();a.Hk=this.Hk;return a};
g.h.transform=function(a){if(!this.Hk)throw Error("Non-simple path");a.transform(this.Nd,0,this.Nd,0,this.Nd.length/2);this.ze&&a.transform(this.ze,0,this.ze,0,1);this.td&&this.ze!=this.td&&a.transform(this.td,0,this.td,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.A(k_,f_);g.A(m_,g.Co);m_.prototype.o=null;m_.prototype.sj=function(){return this.Vg?g.Wh(this.ha()):g.Ga(this.width)&&g.Ga(this.height)?new g.yd(this.width,this.height):null};
m_.prototype.resume=function(){};g.A(c_,g_);g.A(b_,g_);g.A(n_,h_);n_.prototype.clear=function(){g.Yd(this.ha())};
n_.prototype.setSize=function(a,b){var c=this.ha(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.A(o_,k_);var r_;g.A(p_,m_);var Nna=0;g.h=p_.prototype;g.h.Pp=function(){var a=d_(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=d_(this,"g");this.B=d_(this,"defs");this.o=new n_(b,this);a.appendChild(this.B);a.appendChild(b);this.i=a;this.l&&(this.ha().setAttribute("preserveAspectRatio","none"),this.P?this.FA():this.ha().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.FA=function(){if(this.Vg){var a=this.sj();0==a.width?this.ha().style.visibility="hidden":(this.ha().style.visibility="",this.o.ha().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Vh(this.ha(),a,b)};
g.h.sj=function(){if(!g.Eh)return this.Vg?g.Wh(this.ha()):p_.Ha.sj.call(this);var a=this.width,b=this.height,c=g.v(a)&&-1!=a.indexOf("%"),d=g.v(b)&&-1!=b.indexOf("%");if(!this.Vg&&(c||d))return null;if(c){var e=this.ha().parentNode;var f=g.Wh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ha().parentNode,f=f||g.Wh(e),b=parseFloat(b)*f.height/100);return new g.yd(a,b)};
g.h.clear=function(){this.o.clear();g.Yd(this.B);this.g={}};
g.h.ij=function(){p_.Ha.ij.call(this);this.P&&this.O.Na(Ona(),"tick",this.FA)};
g.h.T=function(){delete this.g;delete this.B;delete this.o;this.O.dispose();delete this.O;p_.Ha.T.call(this)};g.t(t_,g.RK);g.h=t_.prototype;
g.h.load=function(){g.RK.prototype.load.call(this);if(!v_(g.X(this.player).playerStyle)){var a=g.XB(this.player.getVideoData());if(a)a=s_(a,u_(this)),w_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Wc:(0,g.y)(this.lI,this,a),Cc:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Cc.gaming="1");this.O&&(a.Cc.ptype="embedded");var c=this.player.getVideoData().av;c&&(a.rb={ad_tracking:c});if(b=g.WB(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Wq(b,a)}}};
g.h.unload=function(){w_(this,null);this.o&&(this.o.abort(),this.o=null);g.RK.prototype.unload.call(this)};
g.h.ac=function(a,b){if(!v_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=s_(b,"new");w_(this,c);return!0}return null};
g.h.getOptions=function(){return v_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.lI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=s_(c,u_(this)))}w_(this,c)};
g.h.ib=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<x2.length;f++){var k=Math.abs(b.width-x2[f]);if(-1==e||d>=k)e=f,d=k}d=y2[e];this.l&&g.Ch(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Vh(e.element,Math.round(k.width*a.width),f);g.Kh(e.element,m,n);g.lo(e.element,hpa);m=k.left+k.width/2;k=k.top+l/2;g.L(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.lo(e.element,y2);g.L(e.element,d);(e=g.Id(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ch(e,"height",f+"px")}}}}};
g.h.vE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.rK(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(h0(this,this.i.impressionUrls),(a=g.pt())&&this.i.visualElement&&g.bt(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");h0(this,c.impressionUrls);
(b=g.pt())&&g.bt(b,c.visualElement);g.X(this.player).ub&&this.player.ma("endscreenelementshown",a)}};
g.h.wE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.ko(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.ko(b,"ytp-ce-shown");g.X(this.player).ub&&this.player.ma("endscreenelementhidden",a)}};
g.h.gL=function(a){var b=this;a.target===window&&(new g.N(function(){for(var c in b.g)g.lo(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.ry=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.io(c,"ytp-ce-element");){g.io(c,"subscribe-label")&&i0(this,a);if(g.io(c,"ytp-ce-channel-subscribe"))return;c=g.ce(c)}if(!c||g.io(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Hr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.On?(i0(this,a),this.Lz(),this.player.pauseVideo(),c=g.Dc(a.targetUrl),c=g.Ac(c),g.KL(c,void 0,a.Xc)):(c=this.player.getVideoData().Sb,
c=(0,g.y)(this.QL,this,c,a.targetUrl,a.Xc),c=(0,g.y)(this.Lz,this,c),i0(this,a,c))}}};
g.h.QL=function(a,b,c){var d=g.Dq(b);a&&d&&(d.v||d.list)?g.iY(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.JL(b,c)};
g.h.Oq=function(a,b){g.io(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.L(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.N(function(){g.L(a.element,"ytp-ce-element-hover")},200)).start():g.L(a.element,"ytp-ce-element-hover"),h0(this,b.zD),g0(this,b.id,!0))};
g.h.Hr=function(a,b){g.ko(a.element,"ytp-ce-element-hover");g.ko(a.element,"ytp-ce-force-expand");g0(this,b.id,!1)};
g.h.Lz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var x2=[346,426,470,506,570,640,853,1280,1920],y2="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Zna={rN:"current",yO:"new"};var aoa={CLOSE:"close",CO:"openUrl",HB:"subscribe"},boa={mN:"click",CLOSE:"close",UN:"hidden",cP:"rollOut",DB:"rollOver",EB:"shown"};var doa={HP:"xx",IP:"xy",JP:"yx",KP:"yy"};g.t(D0,w0);var ioa={cB:"anchored",YO:"rect",fP:"shapeless"};var moa={CLOSED:"closed",LO:"playerControlShow",DB:"rollOver",EB:"shown"};H0.prototype.Hb=function(){var a=uoa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
H0.prototype.showLinkIcon=function(){return J0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var I0={cB:"anchored",fB:"branding",CHANNEL:"channel",qN:"cta",WN:"highlightText",kO:"label",PLAYLIST:"playlist",OO:"popup",jP:"speech",HB:"subscribe",tP:"title",VIDEO:"video",DP:"website"},qoa={fB:"branding",dN:"card",xN:"drawer",VN:"highlight",sO:"marker",TO:"promotion",TEXT:"text",FP:"widget"},roa={BP:"video_relative",MO:"player_relative"};Q0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Ob(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.N(this.u,a,d))};R0.prototype.ha=function(){return this.u};
R0.prototype.l=function(){};var V0={bevel:1,dropshadow:2};g.t($0,R0);
$0.prototype.l=function(a,b){var c=N0(a);if(c){var d=A0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=M0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.th(y0(b,z0(e,new g.qh(e.D,e.F,e.Li,e.l),b.g))),k=d.clone();c=new g.qh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=Y0(k,c.effects);l=S0(this,k.width,k.height);m=X0(c,k.width,k.height,this.g);
d=new g.qh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.wd(f.x-k.left,f.y-k.top);this.o=17*v0(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&K0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new l_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Coa(d,n);var u=this.A(d,e,n,r),z=n.x;n=n.y;var C=d.width,E=d.height,F=d.left;d=d.top;var K=new i_;K.moveTo(F+e+p,d+p);"t"==r&&(K.ec(u.start,d+p),K.ec(z,n),K.ec(u.end,d+p));K.ec(F+C-e-p,d+p);j_(K,e,e,-90);"r"==r&&(K.ec(F+C-p,u.start),K.ec(z,n),K.ec(F+
C-p,u.end));K.ec(F+C-p,d+E-e-p);j_(K,e,e,0);"b"==r&&(K.ec(u.end,d+E-p),K.ec(z,n),K.ec(u.start,d+E-p));K.ec(F+e+p,d+E-p);j_(K,e,e,90);"l"==r&&(K.ec(F+p,u.end),K.ec(z,n),K.ec(F+p,u.start));K.ec(F+p,d+e+p);j_(K,e,e,180);K.close();q_(l,K,f,m);if(m=this.ha())g.L(m,"annotation-shape"),g.L(m,"annotation-speech-shape"),g.Kh(m,k.left,k.top),g.Vh(m,k.width,k.height),Z0(l,m,c.effects)}}}};
$0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.sd(k-f/2,l+b,l+m-f-b);return new g.Ci(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Ci(0,0)};g.t(a1,R0);a1.prototype.l=function(a,b){var c=N0(a);if(c){var d=A0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=Y0(d,e.effects);var f=S0(this,c.width,c.height),k=new l_(!e.l&&this.g?1:e.l,e.bgColor),l=new b_("#000",0);d=W0(new g.qh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);q_(f,d,k,l);f=this.ha();g.L(f,"annotation-shape");e=e.g;KZ(f,this.g?Math.max(e,.9):e);g.Kh(f,c.left,c.top);g.Vh(f,c.width,c.height)}}};g.t(b1,R0);
b1.prototype.l=function(a,b){var c=N0(a);if(c){var d=A0(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=Y0(d,c.effects),f=S0(this,e.width,e.height),k=new g.qh(0,0,d.width,d.height);d=X0(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&K0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new l_(p,n?m.i:m.borderColor):null;k=W0(k,l,m?m.g/2+1:0);q_(f,k,m,d);if(k=this.ha())g.L(k,"annotation-shape"),g.L(k,"annotation-popup-shape"),g.Kh(k,e.left,e.top),g.Vh(k,e.width,e.height),Z0(f,k,c.effects)}}};g.t(c1,$0);c1.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Ci(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Ci(0,0)};g.t(d1,g.H);g.h=d1.prototype;g.h.fx=function(){this.F||(this.o&&g.Xh(this.o,!0),this.u&&g.Xh(this.u,!0),this.l&&(this.l.g=!0,KZ(this.i,i1(this)?1:0),this.l.l(this.g,f1(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.ba.wm(g.oK(this.A),"mouseleave",function(a){this.Wm.stop();this.tg(a)}))};
g.h.tg=function(){this.F&&(this.M?this.D.start():this.ew(),this.l&&(this.l.g=!1,KZ(this.i,i1(this)?1:0),this.l.l(this.g,f1(this))),this.F=!1,this.H&&(this.ba.Na(this.H),this.H=null))};
g.h.ew=function(){this.o&&g.Xh(this.o,!1);this.u&&g.Xh(this.u,!1)};
g.h.kF=function(a){this.aa=a;this.Wm.Aj()};
g.h.ZC=function(){var a=this.aa,b=new g.wd(a.clientX,a.clientY),c=g.Oh(this.A.getRootNode()),d=j1(c,this.O);c=(this.u&&LZ(this.u)||this.o&&LZ(this.o))&&j1(c,this.M);d&&d.contains(b)||c&&c.contains(b)?this.fx(a):this.tg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=f1(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new a1:"popup"==this.g.style?d=new b1:"anchored"==this.g.style?d=new $0:"speech"==this.g.style&&(d=new c1);d&&(d.l(this.g,c),this.l=d,c=d.ha())&&(g.Xh(c,!1),g.L(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Ud("DIV",c);g.Xh(this.i,!1);this.g.o&&(this.B=g.Ud("DIV","inner-text"),"label"==this.g.style&&(g.L(this.B,"player-label-text"),this.B.style.backgroundColor=this.g.i.bgColor),g.ee(this.B,this.g.o),this.i.appendChild(this.B));g.Wp(this.i,"annotation_id",this.g.id);this.R(this.i);Doa(this,this.i);if(K0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Hb())c=this.i,d=new g.an(t0(d)),c.title=d.g+d.i;this.u=g.Ud("SPAN","annotation-link-icon");g.Xh(this.u,
!1);this.i.appendChild(this.u)}Eoa(this);K0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=F0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ha()&&(this.l.ha().style.zIndex=a)}g.Xh(this.i,!0);KZ(this.i,i1(this)?1:0);h1(this);this.l&&this.l.ha()&&g.Xh(this.l.ha(),!0)};
g.h.hide=function(){this.i&&g.Xh(this.i,!1);this.l&&this.l.ha()&&g.Xh(this.l.ha(),!1);this.I&&(this.ba.Na(this.I),this.I=null)};g.t(k1,g.H);g.h=k1.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(l1(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.bx,this),this.i.subscribe("onVideoAreaChange",this.Sy,this))};
g.h.destroy=function(){if(this.view){l1(this);var a=this.view,b=a.ba;g.Wr(b.g);b.g.length=0;a.Wm.dispose();a.D.dispose();a.i&&g.$d(a.i);a.l&&a.l.ha()&&g.$d(a.l.ha())}m1(this)};
g.h.Sy=function(){h1(this.view)};
g.h.bx=function(){h1(this.view)};g.t(n1,$Z);g.t(o1,$Z);g.t(p1,o1);g.t(q1,$Z);g.t(r1,$Z);g.t(s1,o1);g.t(t1,o1);g.t(u1,$Z);g.t(v1,$Z);E1.prototype.l=function(a,b){var c=g.je(b.target,"label");c&&g.M(c,"iv-card-poll-choice-focused",a)};
E1.prototype.B=function(a,b){var c=g.je(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.Kd("iv-card-sign-in-button",c).click();else{var d=parseInt(Ena(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;G1(a,c);g.$q(this.g.videoData.Bd,{Cc:{action_poll_vote:1},rb:{poll_id:a.id,index:d,session_token:a.F}});A1(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.pt())&&g.ct(c,a.A)}};
E1.prototype.A=function(a){var b=g.x("yt.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.B)});
O1(this,a,!0,c)};
E1.prototype.D=function(a){var b=g.x("yt.ypc.bootstrap.api.loadOffers");b&&(b=g.Ra(b,a.O,a.F,a.B));O1(this,a,!1,b)};g.t(V1,g.H);g.h=V1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.gE(a,b,{id:c});g.I(this,a);a.namespace="annotations_module";d&&HZ(a).subscribe("onEnter",d,this);e&&HZ(a).subscribe("onExit",e,this);g.wK(this.context.Z,[a])};
g.h.In=function(){this.context.i.subscribe("resize",this.ul,this)};
g.h.ha=function(){return this.Ba};
g.h.Ai=function(a,b,c,d,e,f,k){this.context.g.da(a,"click",g.Ra(this.tm,b,c,d,e,f||[],k||0),this);this.context.g.da(a,"touchstart",g.Ra(function(){this.Vs=!1}),this);
this.context.g.da(a,"touchmove",g.Ra(function(){this.Vs=!0}),this)};
g.h.tm=function(a,b,c,d,e,f,k){if(this.Vs)return!1;k&&(k.stopPropagation(),k.preventDefault());Poa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.D)()};
g.h.hide=function(){};
g.h.destroy=function(){g.$d(this.ha())};
g.h.ul=function(){};g.t(Y1,V1);g.h=Y1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Wh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.ul=function(){var a=this.isAvailable();g.Xh(this.ha(),a);g.M(this.context.Z.getRootNode(),"ytp-iv-drawer-enabled",a);IZ(this.i)};
g.h.destroy=function(){this.i.xi(!1);this.i.getRootNode().removeChild(this.B);g.gq(this.I);g.Wr(this.aa);this.Y&&this.Y.dispose();this.D&&this.D.dispose();V1.prototype.destroy.call(this)};
g.h.LE=function(a){this.M.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Rz=function(a){if(!g.io(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.pt(),c=this.g?this.g.Gb.u:this.H;b&&c&&ZZ(b,[c]);this.g=a;a2(this)}LZ(this.ha())&&(2==this.context.Z.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Z.getAdState():void 0):(b=isNaN(void 0)?this.context.Z.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Z.getCurrentTime()),b&&a.Gb.teaserDurationMs&&this.i.xi(!0,{teaserText:a.Gb.teaserText,durationMs:a.Gb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.M.isActive()&&this.V)&&b2(this,a),this.ka.start(910+a.Gb.teaserDurationMs))}};
g.h.KL=function(a){this.u||(this.g=a,a2(this),b2(this,a),W1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.dC=function(){if(this.u){C1(this.context.logger,this.R,4,c2(this).i.close);var a=g.pt();a&&this.O&&g.ct(a,this.O);X1(this)}};
g.h.nC=function(){g.M(this.B,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.TD=function(){var a=g.pt(),b=c2(this);b=b?b.u:this.H;a&&b&&YZ(a,[b])};
g.h.SD=function(){var a=g.pt(),b=c2(this);b=b?b.u:this.H;a&&b&&ZZ(a,[b])};
g.h.WD=function(){var a=c2(this);D1(this.context.logger,8,a.l,a.i.XL);var b=g.pt();b&&a&&YZ(b,[a.D,a.u])};
g.h.VD=function(){var a=g.pt(),b=c2(this);a&&b&&ZZ(a,[b.D])};
g.h.UD=function(a){var b=c2(this),c=g.pt();this.g?a?(a=this.context.logger,D1(a,9,b.l,b.i.Cs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.ct(c,b.D)):(a=this.context.logger,D1(a,12,b.l,b.i.Cs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.ct(c,b.u)):(a=this.context.logger,C1(a,this.R,12,b.i.Cs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.ct(c,this.H))};
var Z1={collaborator:n1,donation:p1,episode:v1,movie:v1,playlist:q1,poll:r1,productListing:s1,simple:o1,tip:t1,video:u1};g.t(d2,V1);d2.prototype.In=function(){V1.prototype.In.call(this);Xoa(this)};
d2.prototype.show=function(){V1.prototype.show.call(this);var a=g.pt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&YZ(a,[g.Zs(b.itct)])};
d2.prototype.hide=function(){V1.prototype.hide.call(this);var a=g.pt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&ZZ(a,[g.Zs(b.itct)])};g.t(e2,d2);g.h=e2.prototype;g.h.RL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Wh(a);this.g||(g.Uh(a,e.width),g.Uh(b,e.width));g.Ch(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Ch(c,"right","1px");this.o=!0;g.Xh(a,!0);this.A=new g.N(function(){g.L(this.ha(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.xD=function(a,b){g.ko(this.ha(),"iv-branding-active");this.B=new g.N((0,g.y)(function(){g.Xh(a,!1);this.g||g.Uh(b,0)},this),250);
this.B.start();this.o=!1};
g.h.show=function(){if(!this.isActive){d2.prototype.show.call(this);if(!this.D){g.L(this.ha(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Ud("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Xh(this.i,!1);var b=g.Ud("DIV","branding-img-container",this.i);this.ha().appendChild(b);var c=g.Ud("DIV","iv-branding-context-name");g.ee(c,a.channel_name);var d=g.Ud("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.cW(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Z),this.g.g(d);b=g.Ud("DIV","iv-branding-context-subscribe-caret");c=g.Ud("DIV","branding-context-container-inner",b,c,d);g.Xh(c,!1);d=g.Ud("DIV","branding-context-container-outer",c);g.Ch(d,"right",this.u+"px");this.ha().appendChild(d);var e=this.annotation.Hb();e&&this.Ai(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.N(g.Ra(this.xD,c,d),500,this);g.I(this,this.l);this.context.g.da(this.ha(),"mouseover",(0,g.y)(this.RL,this,c,d,b,a.image_height));this.context.g.da(this.ha(),"mouseout",(0,g.y)(this.l.start,this.l,void 0));this.D=!0}z1(this.context.logger,this.annotation.g);g.Xh(this.ha(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=JZ(a).width;c=g.Ga(void 0)?void 0:b;g.Kh(a,c);f=new WZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Gna);g.I(this,f);this.context.l.da(f,
"begin",g.Ra(g.Xh,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(d2.prototype.hide.call(this),g.Xh(this.ha(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);d2.prototype.destroy.call(this)};g.t(f2,d2);g.h=f2.prototype;g.h.show=function(){this.isActive||(d2.prototype.show.call(this),this.H||(Yoa(this),this.H=!0),g.Xh(this.ha(),!0),this.annotation&&this.annotation.g&&z1(this.context.logger,this.annotation.g),g.Kg(function(){g.ko(this.ha(),"iv-promo-inactive")},100,this),this.ha().removeAttribute("aria-hidden"),this.isActive=!0,i2(this),h2(this),j2(this,this.B))};
g.h.hide=function(){this.isActive&&(g.L(this.ha(),"iv-promo-inactive"),this.isActive=!1,this.ha().setAttribute("aria-hidden",!0))};
g.h.tm=function(a,b,c,d,e,f,k){return this.u?!1:d2.prototype.tm.call(this,a,b,c,d,e,f,k)};
g.h.Rp=function(a,b){b.stopPropagation();h2(this);j2(this,a);this.g.focus()};
g.h.bD=function(a){this.F=!0;this.Rp(500,a)};
g.h.aD=function(){this.F=!1;g2(this)};
g.h.SC=function(a){a.stopPropagation();this.hide();B1(this.context.logger,this.annotation.g)};
g.h.TC=function(a){a.stopPropagation();i2(this);this.u=!0;g.L(this.ha(),"iv-promo-collapsed-no-delay");this.A.start();B1(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();d2.prototype.destroy.call(this)};g.t(k2,g.RK);g.h=k2.prototype;g.h.ac=function(a,b){if(!l2(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.mo(b);c&&q2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&($1(this.g,b),IZ(this.player)),!0}return null};
g.h.getOptions=function(){return l2(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Ir=function(){if(this.o){var a=g.oK(this.player).getVideoContentRect(!0);g.Vh(this.o.element,a.width,a.height);g.Kh(this.o.element,a.left,a.top)}if(this.g){var b=g.uK(this.player);a=this.g;b=b.width;g.M(a.B,"iv-drawer-small",426>=b);g.M(a.B,"iv-drawer-big",1280<=b)}};
g.h.CJ=function(a){this.jc(a.state);g.U(a.state,2)&&(this.rd()&&this.xe()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.xi(!1))};
g.h.load=function(){g.RK.prototype.load.call(this);this.jc(g.nK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.y)(this.mI,this,b,this.H),d=(0,g.y)(function(){this.B=null},this);
g.tq()&&(c=r2(this,c));c={format:"XML",Wc:c,onError:d,Cc:{}};a.isPharma&&(c.Cc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Cc.gaming="1");(b=d.I.get(b))&&s2(c,b);b=b&&(b.Al||b.zl);if(!a.nl||b)a.Bd?m2(this,a.Bd,c):(this.l=(0,g.y)(this.uE,this,c),this.player.addEventListener("videodatachange",this.l));g.DK(this.player,this.o.element,4);this.Ir()};
g.h.jc=function(a){a=!a.isCued()&&!g.U(a,1024);g.aD(this.u,a);g.aD(this.o,a)};
g.h.uE=function(a){var b=this.player.getVideoData();b.Bd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),m2(this,b.Bd,a))};
g.h.unload=function(){Ioa(this.D);g.zK(this.player,"annotations_module");g.Kb(this.i,function(a){a.destroy()});
g.Kb(this.O,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,IZ(this.player));this.I=!1;this.B&&(this.B.abort(),this.B=null);this.i={};this.O={};this.u.hide();g.RK.prototype.unload.call(this);g.$C(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.mI=function(a,b,c){this.B=null;if(!o2(this,b,a)&&(a=g.Qq(c)&&c.responseXML?c.responseXML:null)){q2(this,a);g.L(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.gE(c,e,f);a.push(b)}}g.wK(this.player,a)}};
g.h.Ry=function(a){a==this.player.getVideoData().videoId&&(this.loaded?cpa(this):this.load())};
g.h.rE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,t2(this,a),z1(this.D,b.g))};
g.h.sE=function(a){u2(this,a.getId())};
g.h.dw=function(a){a&&(a.hide(),w2(this,"shown",!1,a.annotation.id),this.Jl(a.annotation,"hidden"))};
g.h.dA=function(a){a&&(a.show(),w2(this,"shown",!0,a.annotation.id),this.Jl(a.annotation,"shown"))};
g.h.RK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;L0(d.annotation,function(f){e=e||f.value});
fpa(this,a,b,e)}};
g.h.tH=function(a){if(a&&a.id){var b=a.Hb();if(b){var c=t0(b);if(c){var d=(0,g.y)(this.Jl,this,a,"click");if("new"==U1(c,b.target)||v2(this,b))d(),d=null;A1(this.D,a.g,d)}}}};
g.h.Jl=function(a,b){toa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!v2(this,c.url))){e=T1(c.url);var f=Moa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=p2(this).Z,g.iY(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&p2(this).Z.fc()&&p2(this).Z.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=t0(c.url))?(f=R1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Ra(Noa,e.pageId,e.lc),d=new g.an(d),e=e(d.i),d.i=e,d=d.toString())):d=null,
d&&(this.player.pauseVideo(),c=U1(d,c.url.target),e=a.itct,"ei"in g.Dq(d)&&(d=g.kh(d,"ei")),g.KL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.uI=function(){w2(this,"playerControlShow",!1)};
g.h.tK=function(){w2(this,"playerControlShow",!0)};
g.h.tE=function(a){w2(this,"rollOver",!0,a.id)};
g.h.tg=function(a){w2(this,"rollOver",!1,a.id)};
g.h.WH=function(a){a&&a.id&&(this.i[a.id].l=!0,u2(this,a.id),B1(this.D,a.g),this.Jl(a,"close"),w2(this,"closed",!0,a.id))};
g.h.rd=function(){return!!this.g&&this.g.isAvailable()};
g.h.xe=function(){this.rd();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.rd();this.g&&(a?c?W1(this.g,c,b):W1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):X1(this.g))};
g.h.xi=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.Ry,this);g.ko(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.uq(a[b]);this.M.length=0;g.RK.prototype.T.call(this)};g.kV.annotations_module=k2;g.kV.creatorendscreen=t_;})(_yt_player);
